[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "candidosouza", email = "candidosouzza@gmail.com"},
]
dependencies = [
    "autopep8>=2.0.1",
]
requires-python = ">=3.10.2"
license = {text = "n"}
