name: fc-admin-codeflix-python-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pdm sync -d -G testing
